[toolchain]
channel = "stable"
components = [ "cargo", "rustfmt", "rust-analyzer", "rust-src", "rust-docs", "clippy" ]
targets = [ "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-unknown-linux-gnu"]
profile = "minimal"
